# Generated by Django 4.1 on 2022-09-03 10:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Binary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.BinaryField()),
                ('created_by', models.CharField(default='internal', max_length=250)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Bot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('damage', models.IntegerField(default=0)),
                ('lives', models.IntegerField(default=3)),
                ('x_coordinate', models.IntegerField(default=-1)),
                ('y_coordinate', models.IntegerField(default=-1)),
                ('archive_x_coordinate', models.IntegerField(default=-1)),
                ('archive_y_coordinate', models.IntegerField(default=-1)),
                ('order_number', models.IntegerField(default=0)),
                ('facing_direction', models.CharField(choices=[('NORTH', 'North'), ('EAST', 'East'), ('SOUTH', 'South'), ('WEST', 'West')], max_length=5)),
                ('created_by', models.CharField(default='internal', max_length=250)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_by', models.CharField(default='internal', max_length=250)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('scenario_name', models.CharField(max_length=250)),
                ('current_round', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('AVAILABLE', 'Available'), ('CALCULATING', 'Calculating'), ('FINISHED', 'Finished')], default='CALCULATING', max_length=15)),
                ('created_by', models.CharField(default='internal', max_length=250)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_by', models.CharField(default='internal', max_length=250)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='MovementCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round', models.IntegerField(default=0)),
                ('phase', models.IntegerField(default=3)),
                ('status', models.CharField(choices=[('INITIAL', 'Initial'), ('FINAL', 'Final'), ('LOCKED', 'Locked'), ('FLYWHEEL', 'Flywheel')], default='INITIAL', max_length=10)),
                ('card_definition', models.CharField(choices=[('MC_10', 'Mc 10'), ('MC_20', 'Mc 20'), ('MC_30', 'Mc 30'), ('MC_40', 'Mc 40'), ('MC_50', 'Mc 50'), ('MC_60', 'Mc 60'), ('MC_70', 'Mc 70'), ('MC_80', 'Mc 80'), ('MC_90', 'Mc 90'), ('MC_100', 'Mc 100'), ('MC_110', 'Mc 110'), ('MC_120', 'Mc 120'), ('MC_130', 'Mc 130'), ('MC_140', 'Mc 140'), ('MC_150', 'Mc 150'), ('MC_160', 'Mc 160'), ('MC_170', 'Mc 170'), ('MC_180', 'Mc 180'), ('MC_190', 'Mc 190'), ('MC_200', 'Mc 200'), ('MC_210', 'Mc 210'), ('MC_220', 'Mc 220'), ('MC_230', 'Mc 230'), ('MC_240', 'Mc 240'), ('MC_250', 'Mc 250'), ('MC_260', 'Mc 260'), ('MC_270', 'Mc 270'), ('MC_280', 'Mc 280'), ('MC_290', 'Mc 290'), ('MC_300', 'Mc 300'), ('MC_310', 'Mc 310'), ('MC_320', 'Mc 320'), ('MC_330', 'Mc 330'), ('MC_340', 'Mc 340'), ('MC_350', 'Mc 350'), ('MC_360', 'Mc 360'), ('MC_370', 'Mc 370'), ('MC_380', 'Mc 380'), ('MC_390', 'Mc 390'), ('MC_400', 'Mc 400'), ('MC_410', 'Mc 410'), ('MC_420', 'Mc 420'), ('MC_430', 'Mc 430'), ('MC_440', 'Mc 440'), ('MC_450', 'Mc 450'), ('MC_460', 'Mc 460'), ('MC_470', 'Mc 470'), ('MC_480', 'Mc 480'), ('MC_490', 'Mc 490'), ('MC_500', 'Mc 500'), ('MC_510', 'Mc 510'), ('MC_520', 'Mc 520'), ('MC_530', 'Mc 530'), ('MC_540', 'Mc 540'), ('MC_550', 'Mc 550'), ('MC_560', 'Mc 560'), ('MC_570', 'Mc 570'), ('MC_580', 'Mc 580'), ('MC_590', 'Mc 590'), ('MC_600', 'Mc 600'), ('MC_610', 'Mc 610'), ('MC_620', 'Mc 620'), ('MC_630', 'Mc 630'), ('MC_640', 'Mc 640'), ('MC_650', 'Mc 650'), ('MC_660', 'Mc 660'), ('MC_670', 'Mc 670'), ('MC_680', 'Mc 680'), ('MC_690', 'Mc 690'), ('MC_700', 'Mc 700'), ('MC_710', 'Mc 710'), ('MC_720', 'Mc 720'), ('MC_730', 'Mc 730'), ('MC_740', 'Mc 740'), ('MC_750', 'Mc 750'), ('MC_760', 'Mc 760'), ('MC_770', 'Mc 770'), ('MC_780', 'Mc 780'), ('MC_790', 'Mc 790'), ('MC_800', 'Mc 800'), ('MC_810', 'Mc 810'), ('MC_820', 'Mc 820'), ('MC_830', 'Mc 830'), ('MC_840', 'Mc 840')], max_length=32)),
                ('optional_text', models.CharField(max_length=250)),
                ('created_by', models.CharField(default='internal', max_length=250)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_by', models.CharField(default='internal', max_length=250)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='roborally.bot')),
            ],
        ),
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round', models.IntegerField(default=0)),
                ('phase', models.IntegerField(default=3)),
                ('created_by', models.CharField(default='internal', max_length=250)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='roborally.game')),
                ('snapshot', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='roborally.binary')),
            ],
        ),
        migrations.CreateModel(
            name='Flag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x_coordinate', models.IntegerField(default=-1)),
                ('y_coordinate', models.IntegerField(default=-1)),
                ('archive_x_coordinate', models.IntegerField(default=-1)),
                ('archive_y_coordinate', models.IntegerField(default=-1)),
                ('order_number', models.IntegerField(default=0)),
                ('created_by', models.CharField(default='internal', max_length=250)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_by', models.CharField(default='internal', max_length=250)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='roborally.game')),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round', models.IntegerField(default=0)),
                ('phase', models.IntegerField(default=3)),
                ('type', models.CharField(choices=[('BOT_PUSHES', 'Bot Pushes'), ('CONVEYORBELT_STALL', 'Conveyorbelt Stall'), ('BOT_SHOOTS', 'Bot Shoots'), ('BOARD_SHOOTS', 'Board Shoots'), ('BOT_DIES_DAMAGE', 'Bot Dies Damage'), ('BOT_DIES_HOLE', 'Bot Dies Hole'), ('ARCHIVE_MARKER_MOVED', 'Archive Marker Moved'), ('POWER_DOWN', 'Power Down'), ('BOT_HITS_WALL', 'Bot Hits Wall'), ('BOT_HITS_UNMOVABLE_BOT', 'Bot Hits Unmovable Bot')], max_length=32)),
                ('optional_text', models.CharField(max_length=250)),
                ('created_by', models.CharField(default='internal', max_length=250)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_actors_set', to='roborally.bot')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='roborally.game')),
                ('victim', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_victims_set', to='roborally.bot')),
            ],
        ),
        migrations.AddField(
            model_name='bot',
            name='archive_flag',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='roborally.flag'),
        ),
        migrations.AddField(
            model_name='bot',
            name='game',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='roborally.game'),
        ),
        migrations.AddField(
            model_name='bot',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
