# Generated by Django 4.1 on 2022-09-03 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roborally', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='name',
            field=models.CharField(max_length=250, unique=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='scenario_name',
            field=models.CharField(choices=[('MOVING_TARGETS', 'Moving Targets'), ('TEST', 'Test'), ('AGAINST_THE_GRAIN', 'Against The Grain'), ('TRICKSY', 'Tricksy'), ('ISLAND_KING', 'Island King'), ('ODDEST_SEA', 'Oddest Sea'), ('ROBOT_STEW', 'Robot Stew'), ('LOST_BEARINGS', 'Lost Bearings'), ('WHIRLWIND_TOUR', 'Whirlwind Tour'), ('VAULT_ASSAULT', 'Vault Assault'), ('PILGRIMAGE', 'Pilgrimage'), ('DEATH_TRAP', 'Death Trap'), ('AROUND_THE_WORLD', 'Around The World'), ('BLOODBATH_CHESS', 'Bloodbath Chess'), ('TWISTER', 'Twister'), ('CHOP_SHOP_CHALLENGE', 'Chop Shop Challenge'), ('ISLAND_HOP', 'Island Hop'), ('DIZZY_DASH', 'Dizzy Dash'), ('CHECKMATE', 'Checkmate'), ('RISKY_EXCHANGE', 'Risky Exchange')], max_length=250),
        ),
    ]
