# Generated by Django 4.1 on 2022-09-03 17:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('roborally', '0002_alter_game_name_alter_game_scenario_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bot',
            name='archive_flag',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='roborally.flag'),
        ),
    ]
