# Generated by Django 4.1 on 2022-09-08 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roborally', '0003_alter_bot_archive_flag'),
    ]

    operations = [
        migrations.CreateModel(
            name='BoardElement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('STARTING_BOARD_1', 'Starting Board 1'), ('STARTING_BOARD_2', 'Starting Board 2'), ('MAELSTROM', 'Maelstrom'), ('SPIN_ZONE', 'Spin Zone'), ('VAULT', 'Vault'), ('CROSS', 'Cross'), ('CHESS', 'Chess'), ('CHOP_SHOP', 'Chop Shop')], max_length=20)),
                ('element_type', models.CharField(choices=[('BASIC', 'Type Basic'), ('STARTING_1', 'Type Starting 1'), ('STARTING_2', 'Type Starting 2'), ('STARTING_3', 'Type Starting 3'), ('STARTING_4', 'Type Starting 4'), ('STARTING_5', 'Type Starting 5'), ('STARTING_6', 'Type Starting 6'), ('STARTING_7', 'Type Starting 7'), ('STARTING_8', 'Type Starting 8'), ('REPAIR', 'Type Repair'), ('OPTION', 'Type Option'), ('HOLE', 'Type Hole'), ('SINGLE_CONVEYOR', 'Type Single Conveyor'), ('DUAL_CONVEYOR', 'Type Dual Conveyor'), ('PUSHER_135', 'Type Pusher 135'), ('PUSHER_24', 'Type Pusher 24'), ('ROTATOR_CLOCKWISE', 'Type Rotator Clockwise'), ('ROTATOR_COUNTERCLOCKWISE', 'Type Rotator Counterclockwise'), ('WALL', 'Type Wall'), ('LASER', 'Type Laser')], max_length=50)),
                ('x_coordinate', models.IntegerField(default=-1)),
                ('y_coordinate', models.IntegerField(default=-1)),
                ('direction', models.CharField(blank=True, choices=[('NORTH', 'North'), ('EAST', 'East'), ('SOUTH', 'South'), ('WEST', 'West')], max_length=5, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Scenario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('MOVING_TARGETS', 'Moving Targets'), ('TEST', 'Test'), ('AGAINST_THE_GRAIN', 'Against The Grain'), ('TRICKSY', 'Tricksy'), ('ISLAND_KING', 'Island King'), ('ODDEST_SEA', 'Oddest Sea'), ('ROBOT_STEW', 'Robot Stew'), ('LOST_BEARINGS', 'Lost Bearings'), ('WHIRLWIND_TOUR', 'Whirlwind Tour'), ('VAULT_ASSAULT', 'Vault Assault'), ('PILGRIMAGE', 'Pilgrimage'), ('DEATH_TRAP', 'Death Trap'), ('AROUND_THE_WORLD', 'Around The World'), ('BLOODBATH_CHESS', 'Bloodbath Chess'), ('TWISTER', 'Twister'), ('CHOP_SHOP_CHALLENGE', 'Chop Shop Challenge'), ('ISLAND_HOP', 'Island Hop'), ('DIZZY_DASH', 'Dizzy Dash'), ('CHECKMATE', 'Checkmate'), ('RISKY_EXCHANGE', 'Risky Exchange')], max_length=50)),
                ('turns', models.IntegerField(default=0)),
                ('offset_x', models.IntegerField(default=0)),
                ('offset_y', models.IntegerField(default=0)),
                ('board_name', models.CharField(choices=[('STARTING_BOARD_1', 'Starting Board 1'), ('STARTING_BOARD_2', 'Starting Board 2'), ('MAELSTROM', 'Maelstrom'), ('SPIN_ZONE', 'Spin Zone'), ('VAULT', 'Vault'), ('CROSS', 'Cross'), ('CHESS', 'Chess'), ('CHOP_SHOP', 'Chop Shop')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='ScenarioFlag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('MOVING_TARGETS', 'Moving Targets'), ('TEST', 'Test'), ('AGAINST_THE_GRAIN', 'Against The Grain'), ('TRICKSY', 'Tricksy'), ('ISLAND_KING', 'Island King'), ('ODDEST_SEA', 'Oddest Sea'), ('ROBOT_STEW', 'Robot Stew'), ('LOST_BEARINGS', 'Lost Bearings'), ('WHIRLWIND_TOUR', 'Whirlwind Tour'), ('VAULT_ASSAULT', 'Vault Assault'), ('PILGRIMAGE', 'Pilgrimage'), ('DEATH_TRAP', 'Death Trap'), ('AROUND_THE_WORLD', 'Around The World'), ('BLOODBATH_CHESS', 'Bloodbath Chess'), ('TWISTER', 'Twister'), ('CHOP_SHOP_CHALLENGE', 'Chop Shop Challenge'), ('ISLAND_HOP', 'Island Hop'), ('DIZZY_DASH', 'Dizzy Dash'), ('CHECKMATE', 'Checkmate'), ('RISKY_EXCHANGE', 'Risky Exchange')], max_length=50)),
                ('x_coordinate', models.IntegerField(default=-1)),
                ('y_coordinate', models.IntegerField(default=-1)),
                ('order_number', models.IntegerField(default=0)),
            ],
        ),
    ]
